### ISSUE TITLE
Duplicate of weigthed_average_power()

### ISSUE THREAD

**Issue by sladkovm** [GoldenCheetah/sweatpy#10]
There are 2 + 1 functions:

`algorithms.main.weighted_average_power()` - should be leading, because the name is right and it is already in the right module.

`algorithms.metrics.normalized_power()` - currently it implements both *NP* and *xPower* calculations. Proposal it to convet it to single purpose only `algorithms.main.x_power()`

Another aspect - the `metrics` functions do allow masking with replacement to be specified. It is a useful feature, for data streams with sporadic readings during the standstill. Strava, for example, provides a boolean array for indicating moving/standstill that might be used as a mask.

`algorithms.metrics.relative_intensity()` - shoud move to `algorithms.main` and mention RI only.
`algorithms.metrics.stress_score()` - should be split into `stress_score` and `bike_score`.

**Comment by AartGoossens** [comment]
Agree.

This raises an interesting question for me (I will create a separate issue if you think it's worth discussing more):
Do we want multiple algorithms that calculate alternative (weighted) average powers or do we want one method `weighted_average_power()` (don't pin me on the naming) where we choose a default implementation (e.g. xPower) but users can choose a different implementation by calling the method like `weighted_average_power(algorithm='Coggan')`. This is similar to how I started the `sweat.algorithms.w_prime_balance()`. Note that all the algorithms in this implementation are still available as separate methods (`w_prime_balance_froncioni_skiba_clarke()`, etc.) if a user prefers to go that way.

**Comment by sladkovm** [comment]
It is indeed how I was implementing it in `vmpy` as well.

I propose to keep the general implementation in `metrics.core` and in the `metrics.power` expose different variations explicitly.
