### ISSUE TITLE
Using list comprehensions instead of lamda can be shorter

### ISSUE THREAD

**Issue by piotr-kubica** [GoldenCheetah/sweatpy#16]
https://github.com/GoldenCheetah/sweatpy/blob/25131726bae05261af943bca0213ceea78892fe0/sweat/io/strava.py#L193

ex. 
`y = [ x['min'] for x in zones[type]['zones'] ]`

**Comment by sladkovm** [comment]
Since it returns a list and not a generator I would call it 'list comprehension', but for the rest, I agree - proposed syntax is more concise and arguably more pythonic.

Do you feel like submitting a PR for this?

**Comment by sladkovm** [comment]
Implemented by @piotr-kubica
