### ISSUE TITLE
Duplicate of mean_max() algorithm

### ISSUE THREAD

**Issue by sladkovm** [GoldenCheetah/sweatpy#9]
There are currently two versions:

`algorithms.main.mean_max_power()` - relies on rolling mean calculation
`algorithms.metrics.power_duration_curve()` - relies on calculating diff of accumulated energy and is x4 faster

Proposal:

1. Rename algorithm to `mean_max()` because it can be applied not only to *power* but to *pace* as well
2. Keep faster implementation with data type casting resolved according to the outcome of #5
3. Move it to main, which will serve as a module for the general purpose calculations or according to the outcome of #7

**Comment by AartGoossens** [comment]
1. Agree. Then this method would live in `metrics.core` as well?
2. Totally agree :)
3. Agree. Although I don't like the name "main" I gave it. Do you have a better idea? And do we even want to keep `main` when we're moving to separate heartrate/power/speed modules?

**Comment by sladkovm** [comment]
The `mean_max()` resides in the `core` and in the `metrics.power` we would even have a liberty to call a `power_duration_curve()`.

I propose to transfer the content of `main` to the `core` or to the specific metrics module depending on what it does.

**Comment by AartGoossens** [comment]
👍

**Comment by sladkovm** [comment]
Shall I pick up this issue and implement the project structure agreed in #7 ?

**Comment by AartGoossens** [comment]
Yes if you would like to :)
